/// Task 12.5 closes a gap flagged since 12.1: Tauri v2's ACL only gates
/// *plugin*-provided commands by default, so this app's own commands
/// (registered via `tauri::generate_handler!` in `src/lib.rs`) were
/// callable regardless of `capabilities/default.json` until now.
/// `AppManifest::commands` opts every one of them into the same ACL —
/// each gets an autogenerated `allow-$command`/`deny-$command` permission
/// pair (`$command` **kebab-case**, not the Rust function's own snake_case
/// — permission identifiers only allow lowercase ASCII and hyphens, so
/// `install_model` becomes `allow-install-model` in
/// `capabilities/default.json`, confirmed by an actual build failure
/// before this comment was written, not assumed), and
/// `capabilities/default.json` must name the ones it allows individually
/// (no wildcard), matching this repo's own default-deny convention. Keep
/// this list in sync with `tauri::generate_handler!`'s own list in
/// `src/lib.rs` — a command left out here is simply unrestricted by this
/// layer (`is_allowed()`-style in-app gating, where it exists, still
/// applies); a command listed here with no matching permission in a
/// capability file fails at *build* time, not silently at runtime.
const COMMANDS: &[&str] = &[
    "list_models",
    "list_installed_models",
    "active_model_id",
    "install_model",
    "cancel_install",
    "remove_model",
    "load_model",
    "unload_model",
    "engine_info",
    "generate",
    "cancel_generation",
    "device_info",
    "generate_chat",
    "connector_status",
    "set_search_connector_granted",
    "list_connectors",
    "set_connector_granted",
    "set_search_connector_config",
    "fetch_connector_registry",
    "install_connector",
    "remove_connector",
    "request_calendar_access",
];

fn main() {
    if let Err(error) = tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    ) {
        panic!("tauri-build failed: {error:#}");
    }
}
