// Task 0.3 (native build tooling): declarative Android release signing.
//
// android/ is gitignored and regenerated by `expo prebuild` on every run, so
// signing config can't be hand-edited into app/build.gradle — it has to be
// injected here, the same way llama.rn's own plugin injects Podfile changes.
//
// The real keystore (`release.jks`) and its passwords
// (`release.keystore.properties`) live at the repo root, outside `android/`,
// so they survive `expo prebuild --clean`. Both are gitignored — see
// .gitignore. Gradle checks for the properties file *at build time*, not
// this plugin at prebuild time: when it's absent (e.g. the existing CI smoke
// job in native.yml, or a fresh checkout with no keystore yet), the release
// build type keeps using the debug keystore exactly as it does today.
// Imported from the `expo` package's `config-plugins` subpath rather than
// `@expo/config-plugins` directly: `expo` is a direct dependency, but
// `@expo/config-plugins` is only transitive, and pnpm's strict node_modules
// layout doesn't let a project-root file `require` a transitive dependency.
const { withAppBuildGradle } = require('expo/config-plugins')

const MARKER = 'SOVEREIGN_EDGE_RELEASE_SIGNING'

const RELEASE_SIGNING_CONFIG = `
    def releaseSigningPropsFile = rootProject.file('../release.keystore.properties') // ${MARKER}
    if (releaseSigningPropsFile.exists()) {
        def releaseSigningProps = new Properties()
        releaseSigningProps.load(new FileInputStream(releaseSigningPropsFile))
        release {
            storeFile rootProject.file('../release.jks')
            storePassword releaseSigningProps['storePassword']
            keyAlias releaseSigningProps['keyAlias']
            keyPassword releaseSigningProps['keyPassword']
        }
    }
`

const withAndroidReleaseSigning = (config) =>
  withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        'withAndroidReleaseSigning expects a Groovy app/build.gradle',
      )
    }

    if (config.modResults.contents.includes(MARKER)) {
      return config
    }

    let contents = config.modResults.contents

    contents = contents.replace(
      /(signingConfigs\s*\{\s*\n\s*debug\s*\{[^}]*\}\n)/,
      `$1${RELEASE_SIGNING_CONFIG}`,
    )

    contents = contents.replace(
      /(buildTypes\s*\{\s*\n\s*debug\s*\{[^}]*\}\n\s*release\s*\{\n\s*(?:\/\/[^\n]*\n\s*)*)signingConfig signingConfigs\.debug/,
      "$1signingConfig rootProject.file('../release.keystore.properties').exists() ? signingConfigs.release : signingConfigs.debug",
    )

    config.modResults.contents = contents
    return config
  })

module.exports = withAndroidReleaseSigning
